server:
    port: ${port:8000}
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-request: true
            force-response: true
    tomcat:
        uri-encoding: UTF-8

spring:
    mvc:
        static-path-pattern: /static/**
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: 'jdbc:mariadb://web-study.cdunfdqk1xmg.ap-northeast-2.rds.amazonaws.com:3306/watcha?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true'
        username: 'admin'
        password: '1q2w3e4r'
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 833328981460-m88s7avdlghr78s5c91o7oke6voe8oto.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - email
                            - profile
                    naver:
                        client-id: yH7uZtRaUZDvNIMK61z8
                        client-secret: cQywCAyqAF
                        scope:
                            - email
                            - name
                        client-name: Naver
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8000/login/oauth2/code/naver
                    facebook:
                        client-id: 640823494283533
                        client-secret: abb0bc5ebc2378da236667dcb784bcbd
                        redirect-uri: http://localhost:8000/login/oauth2/code/facebook
                        scope:
                            - public_profile
                            - email
                    kakao:
                        client-id: bc96dc1c2daee8531f566161860afd8c
                        client-secret: 4ycTuEUAWdppYwPnwmbM12TEcMtMnVEz
                        client-name: Kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8000/login/oauth2/code/kakao
                        client-authentication-method: POST
                        scope:
                            - profile_nickname
                            - account_email 
                        

                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB

mybatis:
    mapper-locations:
        - /mappers/*.xml
#file:
#  path: C:/Users/user/OneDrive/?? ??/security_jaean/upload/
